dataset_path: data/dataset/semantickitti/voteflow_preprocess
checkpoint: checkpoints/voteflow_best_m8n128_ori.ckpt
res_name: flow_est  # result name, will be saved in outputs/{res_name}/ and HDF5 files
batch_size: 1  # batch size for inference

# no need to change
defaults:
  - hydra: default
  - model: voteflow
seed: 42069
gpus: 1
slurm_id: 00000
output: ${model.name}-${slurm_id}

